# Generated by Django 6.1 on 2026-09-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('row', 'seat')},
        ),
    ]
